kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  labels:
    app: mongo-pv
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo-data"
