apiVersion: v1
kind: Service
metadata:
    name: mongo-svc
    namespace: wl-ns
spec:
  selector:
    app: mongo
  ports:
  - name: mongo-service
    protocol: TCP
    port: 27017
    targetPort: 27017
